server {
    listen 0.0.0.0:8080;
    listen [::]:8080;

    server_name localhost;

    root /usr/share/nginx/html;  # The root where your Angular app is placed
    index index.html index.htm;

    location / {
        try_files $uri $uri/ /index.html;
    }
}
